name: generate animation

on:
  # run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
