name: generate animation

on:
  # run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
